[package]
name = "graphivo"
version = "0.1.0"
description = "A desktop AWS topology explorer"
authors = ["Basil"]
edition = "2021"

[lib]
name = "graphivo_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
aws-config = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-ec2 = "1"
aws-sdk-rds = "1"
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
tokio = { version = "1", features = ["macros"] }
